using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace T3Pr1SebastianZadomen
{
    public class HydroelectricSystem : EnergySystem, IEnergyCalculation
    {
        public double WaterFlow { get; set; }

        public double HydroelectricEnergyGenerated(double waterFlow)
        {
            return waterFlow * 9.8 * 0.8;
        }

        public override void Simulate()
        {
            
            Console.WriteLine("Enter the water flow (m3/s):");
            WaterFlow = Convert.ToDouble(Console.ReadLine());

            EnergyGenerated = HydroelectricEnergyGenerated(WaterFlow);
            Console.WriteLine($"Energy generated by the hydroelectric system: {EnergyGenerated} kWh");
        }

        public double SolarEnergyGenerated(double sunHours)
        {
            throw new NotImplementedException();
        }

        public double WindEnergyGenerated(double windSpeed)
        {
            throw new NotImplementedException();
        }
    }
}