using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace T3Pr1SebastianZadomen
{
        public class SolarSystem : EnergySystem, IEnergyCalculation
        {
            public double SunHours { get; set; }

        public SolarSystem(double hours)
        {
            SunHours = hours;
        }
        public double SolarEnergyGenerated(double sunHours)
            {
                return sunHours * 1.5;
            }

            public override void Simulate()
            {
               
                Console.WriteLine("Enter the available sun hours:");
                SunHours = Convert.ToDouble(Console.ReadLine());

                EnergyGenerated = SolarEnergyGenerated(SunHours);
                Console.WriteLine($"Energy generated by the solar system: {EnergyGenerated} kWh");
            }

            public double WindEnergyGenerated(double windSpeed)
            {
                throw new NotImplementedException();
            }

            public double HydroelectricEnergyGenerated(double waterFlow)
            {
                throw new NotImplementedException();
            }
        }

}
