using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace T3Pr1SebastianZadomen
{
    public class WindSystem : EnergySystem, IEnergyCalculation
    {
        public double WindSpeed { get; set; }

        public double WindEnergyGenerated(double windSpeed)
        {
            return Math.Pow(windSpeed, 3) * 0.2;
        }

        public override void Simulate()
        {
            Console.WriteLine("Enter the wind speed (m/s):");
            WindSpeed = Convert.ToDouble(Console.ReadLine());

            EnergyGenerated = WindEnergyGenerated(WindSpeed);
            Console.WriteLine($"Energy generated by the wind system: {EnergyGenerated} kWh");
        }

        public double SolarEnergyGenerated(double sunHours)
        {
            throw new NotImplementedException();
        }

        public double HydroelectricEnergyGenerated(double waterFlow)
        {
            throw new NotImplementedException();
        }
    }
}